// Topic configuration: keywords for each topic
// This ensures each topic page shows ONLY relevant content

export interface TopicConfig {
  name: string;
  description: string;
  icon: string;
  keywords: string[];
}

export const topicConfigs: Record<string, TopicConfig> = {
  "cellular-health": {
    name: "Cellular Health",
    description: "Explore the latest research on cellular health, aging, and longevity.",
    icon: "🧬",
    keywords: [
      "cellular",
      "cell",
      "mitochondria",
      "mitochondrial",
      "telomere",
      "telomeres",
      "senescence",
      "senescent",
      "autophagy",
      "dna repair",
      "stem cell",
      "epigenetic",
      "epigenetics",
      "aging mechanism",
      "apoptosis",
      "oxidative stress",
      "inflammation",
      "sirtuin",
      "sirtuins",
      "mtor",
      "ampk",
      "foxo",
      "nrf2",
      "nucleus",
      "cytoplasm",
      "ribosome",
      "endoplasmic reticulum",
      "lysosome",
      "proteasome",
      "cellular aging",
      "cell death",
      "cellular repair",
      "cellular function",
    ],
  },
  supplements: {
    name: "Supplements",
    description: "Evidence-based information on supplements for healthspan and longevity.",
    icon: "💊",
    keywords: [
      "supplement",
      "supplements",
      "vitamin",
      "vitamins",
      "mineral",
      "minerals",
      "magnesium",
      "zinc",
      "iron",
      "calcium",
      "selenium",
      "potassium",
      "iodine",
      "chromium",
      "manganese",
      "copper",
      "multivitamin",
      "nmn",
      "nicotinamide mononucleotide",
      "nr",
      "nicotinamide riboside",
      "nad",
      "nad+",
      "nad plus",
      "resveratrol",
      "quercetin",
      "fisetin",
      "coq10",
      "coenzyme q10",
      "ubiquinol",
      "omega-3",
      "omega 3",
      "fish oil",
      "epa",
      "dha",
      "probiotic",
      "probiotics",
      "prebiotic",
      "prebiotics",
      "metformin",
      "rapamycin",
      "spermidine",
      "curcumin",
      "turmeric",
      "green tea",
      "egcg",
      "creatine",
      "beta-alanine",
      "carnitine",
      "alpha-lipoic acid",
      "ala",
      "nac",
      "n-acetylcysteine",
      "glucosamine",
      "chondroitin",
      "collagen",
      "peptides",
      "berberine",
      "ashwagandha",
      "rhodiola",
      "ginseng",
      "melatonin",
      "glycine",
      "taurine",
      "carnosine",
    ],
  },
  nutrition: {
    name: "Nutrition",
    description: "Nutrition strategies and research for optimal health and longevity.",
    icon: "🥗",
    keywords: [
      "nutrition",
      "diet",
      "dietary",
      "food",
      "foods",
      "meal",
      "meals",
      "eating",
      "calorie",
      "calories",
      "protein",
      "carb",
      "carbs",
      "carbohydrate",
      "carbohydrates",
      "fat",
      "fats",
      "fiber",
      "fibre",
      "antioxidant",
      "antioxidants",
      "polyphenol",
      "polyphenols",
      "mediterranean",
      "plant-based",
      "keto",
      "ketogenic",
      "paleo",
      "vegan",
      "vegetarian",
      "macronutrient",
      "macronutrients",
      "micronutrient",
      "micronutrients",
      "amino acid",
      "amino acids",
      "fatty acid",
      "fatty acids",
      "nutrient",
      "nutrients",
      "micronutrient",
      "macronutrient",
      "hydration",
      "water intake",
      "sodium",
      "sugar",
      "processed food",
      "whole food",
      "nutrient density",
    ],
  },
  fasting: {
    name: "Fasting",
    description: "Intermittent fasting, time-restricted eating, and their health benefits.",
    icon: "⏰",
    keywords: [
      "fasting",
      "intermittent fasting",
      "if",
      "time-restricted",
      "tre",
      "autophagy",
      "ketosis",
      "fasted",
      "meal timing",
      "eating window",
      "omad",
      "one meal a day",
      "16:8",
      "18:6",
      "20:4",
      "water fast",
      "extended fast",
      "fasting protocol",
      "metabolic flexibility",
      "glycogen",
      "fasting benefits",
    ],
  },
  exercise: {
    name: "Exercise",
    description: "Exercise protocols and fitness strategies for longevity.",
    icon: "🏃",
    keywords: [
      "exercise",
      "exercises",
      "workout",
      "workouts",
      "training",
      "fitness",
      "strength",
      "cardio",
      "cardiovascular",
      "resistance",
      "aerobic",
      "anaerobic",
      "muscle",
      "muscles",
      "endurance",
      "hiit",
      "high intensity",
      "zone 2",
      "zone 5",
      "vo2 max",
      "vo2max",
      "heart rate",
      "recovery",
      "mobility",
      "flexibility",
      "stretching",
      "yoga",
      "pilates",
      "running",
      "cycling",
      "swimming",
      "walking",
      "weightlifting",
      "powerlifting",
      "bodyweight",
      "calisthenics",
      "sprint",
      "sprinting",
      "lactate threshold",
      "muscle mass",
      "bone density",
      "injury prevention",
      "performance",
    ],
  },
  sleep: {
    name: "Sleep",
    description: "Sleep optimization, circadian rhythms, and recovery strategies.",
    icon: "😴",
    keywords: [
      "sleep",
      "circadian",
      "melatonin",
      "insomnia",
      "rem",
      "rem sleep",
      "deep sleep",
      "sleep quality",
      "sleep hygiene",
      "bedtime",
      "wake up",
      "sleeping",
      "slept",
      "asleep",
      "sleep cycle",
      "sleep deprivation",
      "nrem",
      "nrem sleep",
      "sleep stages",
      "sleep duration",
      "sleep efficiency",
      "sleep apnea",
      "restless leg",
      "blue light",
      "sleep environment",
      "sleep tracking",
      "sleep debt",
    ],
  },
  "mental-health": {
    name: "Mental Health",
    description: "Mental wellness, cognitive health, and brain longevity strategies.",
    icon: "🧠",
    keywords: [
      "mental health",
      "cognitive",
      "cognition",
      "brain",
      "neuro",
      "neural",
      "neurological",
      "mental",
      "depression",
      "anxiety",
      "stress",
      "mood",
      "memory",
      "memories",
      "focus",
      "attention",
      "dementia",
      "alzheimer",
      "alzheimer's",
      "parkinson",
      "parkinson's",
      "neuroplasticity",
      "neurogenesis",
      "bdnf",
      "serotonin",
      "dopamine",
      "gaba",
      "glutamate",
      "psychology",
      "psychiatric",
      "wellbeing",
      "well-being",
      "cognitive decline",
      "brain health",
      "mental clarity",
      "executive function",
      "processing speed",
      "working memory",
      "neurotransmitter",
      "mental resilience",
      "cognitive training",
      "brain training",
    ],
  },
  hormones: {
    name: "Hormones",
    description: "Hormonal health, optimization, and age-related changes.",
    icon: "⚗️",
    keywords: [
      "hormone",
      "hormones",
      "hormonal",
      "testosterone",
      "estrogen",
      "estradiol",
      "progesterone",
      "cortisol",
      "insulin",
      "insulin resistance",
      "thyroid",
      "tsh",
      "t3",
      "t4",
      "gh",
      "growth hormone",
      "hgh",
      "igf-1",
      "igf1",
      "dhea",
      "dhea-s",
      "melatonin",
      "leptin",
      "ghrelin",
      "adrenaline",
      "epinephrine",
      "norepinephrine",
      "endocrine",
      "hormone replacement",
      "hrt",
      "trt",
      "hormone imbalance",
      "hormone optimization",
      "hormone therapy",
      "androgen",
      "estrogen dominance",
      "hypothyroidism",
      "hyperthyroidism",
      "adrenal",
      "pituitary",
      "hormone panel",
    ],
  },
  protocols: {
    name: "Protocols",
    description: "Comprehensive longevity protocols and health optimization strategies.",
    icon: "📋",
    keywords: [
      "protocol",
      "routine",
      "regimen",
      "program",
      "plan",
      "strategy",
      "optimization",
      "longevity protocol",
      "health protocol",
      "intervention",
      "lifestyle",
      "biohacking",
      "healthspan",
      "lifespan",
      "anti-aging",
      "rejuvenation",
      "prevention",
      "wellness",
      "health optimization",
    ],
  },
  research: {
    name: "Research",
    description: "Latest longevity research, studies, and scientific breakthroughs.",
    icon: "🔬",
    keywords: [
      "research",
      "study",
      "studies",
      "clinical trial",
      "scientific",
      "publication",
      "journal",
      "finding",
      "discovery",
      "evidence",
      "data",
      "analysis",
      "peer review",
      "meta-analysis",
      "systematic review",
      "longitudinal study",
      "cohort study",
      "randomized controlled trial",
      "rct",
      "hypothesis",
      "methodology",
      "results",
    ],
  },
  biomarkers: {
    name: "Biomarkers",
    description: "Biomarker testing, tracking, and optimization for healthspan.",
    icon: "📊",
    keywords: [
      "biomarker",
      "blood test",
      "lab test",
      "cholesterol",
      "glucose",
      "hba1c",
      "crp",
      "testosterone",
      "vitamin d",
      "b12",
      "testing",
      "metrics",
      "tracking",
      "hdl",
      "ldl",
      "triglycerides",
      "insulin sensitivity",
      "fasting glucose",
      "blood pressure",
      "inflammatory markers",
      "hormone levels",
      "biomarker panel",
      "health metrics",
    ],
  },
  genetics: {
    name: "Genetics",
    description: "Genetic factors in longevity, personalized health, and genomics.",
    icon: "🧪",
    keywords: [
      "genetic",
      "gene",
      "genome",
      "dna",
      "snp",
      "mutation",
      "hereditary",
      "inherited",
      "genomic",
      "genotype",
      "phenotype",
      "ancestry",
      "genetic testing",
      "genome sequencing",
      "genetic variant",
      "allele",
      "heritability",
      "genetic predisposition",
      "personalized medicine",
      "pharmacogenomics",
      "gene expression",
      "epigenetic",
    ],
  },
};

/**
 * Get topic configuration by slug
 */
export function getTopicConfig(slug: string): TopicConfig | null {
  return topicConfigs[slug] || null;
}

/**
 * Get all topic slugs
 */
export function getAllTopicSlugs(): string[] {
  return Object.keys(topicConfigs);
}
